
all:
	latexmk -pdf planeringsrapport.tex

clean:
	rm planeringsrapport.aux planeringsrapport.bbl planeringsrapport.blg planeringsrapport.fdb_latexmk planeringsrapport.fls planeringsrapport.log planeringsrapport.out
